### ISSUE TITLE
BUG REPORT: Under Vite-Migration UNABLE TO RUN DEV SERVER

### ISSUE THREAD

**Issue by Aakansh-C** [JCS-Computer-Science/project-module-1-project-flip#78]
Under the Vite-Migration Branch there is a project-flip-module folder. 
Inside this folder lays a vue-cli and vite build.
If you are to open the project-flip-module folder and attempt to run a dev server, it will result in an error; Due to the 2 file builds.

And So, to solve the issue and work around it, open the Project_Flip-Vite folder directly to run a dev server and continue working.
While we confirm everything has been transferred. After which the old build will be terminated.

**Comment by ProFireDev** [comment]
fixed for most builds
