### ISSUE TITLE
Image upload issue

### ISSUE THREAD

**Issue by ProFireDev** [JCS-Computer-Science/project-module-1-project-flip#97]
borrow this as a cdn

**Comment by ProFireDev** [comment]
![image](https://user-images.githubusercontent.com/34112557/150007623-f7caf119-2822-41ee-8bb4-89349162e22a.png)

**Comment by MarkRJJ** [comment]
![Sky_1](https://user-images.githubusercontent.com/89943490/150007805-0bf19e35-eeff-4540-9533-1474e90ef40e.jpg)

**Comment by ProFireDev** [comment]
gonna use this as a hacky work around

**Comment by ProFireDev** [comment]
![image](https://user-images.githubusercontent.com/34112557/151027661-84533466-38c0-4f44-974c-c850e5918e24.png)

**Comment by ProFireDev** [comment]
![Product-page Background](https://user-images.githubusercontent.com/34112557/151050212-79ca8085-87a5-437a-9d03-3b237df6129e.png)

**Comment by ProFireDev** [comment]
![Sky_PC](https://user-images.githubusercontent.com/34112557/151050697-31f122ff-233e-4f61-af79-abf605379931.png)

**Comment by ProFireDev** [comment]
![Contact page filler 3](https://user-images.githubusercontent.com/34112557/151051374-a2746a34-8a66-4160-b102-46f647b70e23.png)
